services:
  identity:
    image: dev.identity.svc:v1.1
    container_name: dev.identity.svc
    build:
      context: ./
      dockerfile: identity.svc/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - dev_network
    ports:
      - 8888:80
    depends_on:
      - session
      - postgresql
      - mongodb

  session:
    image: dev.session.svc.pri:v1.1
    container_name: dev.session.svc.pri
    build:
      context: ./
      dockerfile: session.svc.pri/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - dev_network
    ports:
      - 7002:80
    depends_on:
      - redis
      - mongodb

  monitor:
    image: dev.monitor.svc.pri:v1.1
    container_name: dev.monitor.svc.pri
    build:
      context: ./
      dockerfile: monitor.svc.pri/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    networks:
      - dev_network
    ports:
      - 7003:80
    depends_on:
      - mongodb
   
  redis:
    image: dev.redis:v1.1
    container_name: dev.redis
    build:
      context: ./
      dockerfile: redis/Dockerfile.dev
    networks:
      - dev_network
    ports:
      - 6380:6379

  postgresql:
    image: postgres:15.1
    container_name: dev.postgresql
    environment:
      POSTGRES_PASSWORD: user
    networks:
      - dev_network
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data 

  nginx:
    image: dev.ngx-gate:v1.1
    container_name: dev.ngx-gate
    build:
      context: ./
      dockerfile: nginx/Dockerfile.dev
    networks:
      - dev_network
    ports:
      - 8800:80
    depends_on:
      - identity

  mongodb:
    image: mongo:4.4.17
    container_name: dev.mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: user
    networks:
      - dev_network
    ports:
      - 27018:27017
    volumes:
      - mongodb:/data/db   
      - mongo_config:/data/configdb

volumes:
    postgres:
    mongodb:
    mongo_config:

networks:
  dev_network:


    
