# -------- CREATE nginx gate for DEV env ----------------

FROM nginx:1.23.2

RUN rm /etc/nginx/nginx.conf /etc/nginx/conf.d/default.conf 

COPY nginx/conf.dev /etc/nginx/
COPY nginx/index.html   /usr/share/nginx/html/

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]