#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app
EXPOSE 80

ENV ASPNETCORE_ENVIRONMENT Development

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["identity.svc/identity.svc.csproj", "identity.svc/"]
COPY ["fsp.lib/fsp.lib.csproj", "fsp.lib/"]
RUN dotnet restore "identity.svc/identity.svc.csproj"
COPY . .
WORKDIR "/src/identity.svc"
RUN dotnet build "identity.svc.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "identity.svc.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "identity.svc.dll"]